# .streamlit/config.toml

[theme]
# acento (checkboxes, lines, active states)
primaryColor = "#2d2e83"

# background
backgroundColor = "#ffffff"

# sidebar
secondaryBackgroundColor = "#f8f9fa"

# main text color
textColor = "#000000"

# Font
font = "sans serif"